baseURL = "http://example.org/"
languageCode = "en-us"
title = "Kate and Brett are getting married"
theme = "icon"

[params]
  author = "Your name"
  description = "Cool description"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "background.jpg"
  title = "Brett & Kate"
  description = "are getting married!"

# Footer section
[params.footer]
  enable = true
  note = ""
